use crate::agent::plan::PlanOutput;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FilesInput {
    pub plan: PlanOutput,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct FilesOutput {
    pub files: BTreeMap<String, String>,
}

pub struct FilesNode;

impl FilesInput {
    pub fn new(plan: PlanOutput) -> FilesInput {
        FilesInput { plan }
    }
}

impl FilesNode {
    pub fn new() -> Self {
        Self
    }

    pub async fn run(&self, input: FilesInput) -> anyhow::Result<FilesOutput> {
        Ok(generate_files(input.plan))
    }
}

fn generate_files(plan: PlanOutput) -> FilesOutput {
    let mut files = BTreeMap::new();

    files.insert("package.json".to_string(), package_json(&plan.project_name));

    files.insert(
        "src/App.tsx".to_string(),
        app_tsx(&plan.project_name, &plan.description),
    );

    files.insert("src/main.tsx".to_string(), main_tsx());

    files.insert("src/styles.css".to_string(), styles_css());

    FilesOutput { files }
}

fn package_json(project_name: &str) -> String {
    const PKG_TEMPLATE: &str = r#"{{
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "@vitejs/plugin-react": "latest",
    "vite": "latest",
    "react": "latest",
    "react-dom": "latest",
    "typescript": "latest"
  }},
  "devDependencies": {{}},
  "name": "{}",
  "version": "1.0.0"
}}"#;
    let pkg_name = sanitize_package_name(project_name);
    format!("{} {}", PKG_TEMPLATE, pkg_name)
}

fn sanitize_package_name(project_name: &str) -> String {
    let sanitized = project_name
        .trim()
        .to_lowercase()
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' {
                ch
            } else if ch.is_whitespace() || ch == '_' {
                '-'
            } else {
                '-'
            }
        })
        .collect::<String>();

    let sanitized = sanitized.trim_matches('-').to_string();

    if sanitized.is_empty() {
        "rust-agent-app".to_string()
    } else {
        sanitized
    }
}

fn app_tsx(project_name: &str, description: &str) -> String {
    format!(
        r#"import React from "react";
import "./styles.css";

export default function App() {{
  return (
    <main className="app">
      <section className="hero">
        <p className="eyebrow">Generated by rust_agent</p>
        <h1>{}</h1>
        <p>{}</p>
      </section>
    </main>
  );
}}
"#,
        escape_jsx_text(project_name),
        escape_jsx_text(description)
    )
}

fn escape_jsx_text(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn main_tsx() -> String {
    r#"import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
"#
    .to_string()
}

fn styles_css() -> String {
    r#"* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: #0f172a;
  color: #f8fafc;
}

.app {
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 48px;
}

.hero {
  width: min(720px, 100%);
  padding: 40px;
  border-radius: 28px;
  background: linear-gradient(135deg, rgba(59, 130, 246, 0.24), rgba(168, 85, 247, 0.24));
  border: 1px solid rgba(255, 255, 255, 0.16);
  box-shadow: 0 24px 80px rgba(15, 23, 42, 0.45);
}

.eyebrow {
  margin: 0 0 12px;
  color: #93c5fd;
  font-size: 14px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}

h1 {
  margin: 0 0 16px;
  font-size: clamp(40px, 8vw, 72px);
  line-height: 1;
}

p {
  margin: 0;
  color: #cbd5e1;
  font-size: 18px;
  line-height: 1.7;
}
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use crate::agent::files::{FilesInput, FilesNode, escape_jsx_text, sanitize_package_name};
    use crate::agent::plan::{ComponentPlan, PagePlan, PlanOutput};

    #[tokio::test]
    async fn generates_minimum_sandpack_files() {
        let node = FilesNode::new();

        let output = node
            .run(FilesInput::new(PlanOutput {
                project_name: "Todo App".to_string(),
                description: "A todo management application".to_string(),
                pages: vec![PagePlan {
                    name: "Home".to_string(),
                    route: "/".to_string(),
                    purpose: "Display todos".to_string(),
                }],
                components: vec![ComponentPlan {
                    name: "TodoList".to_string(),
                    purpose: "Render todos".to_string(),
                }],
            }))
            .await
            .expect("files node should generate files");

        assert!(output.files.contains_key("package.json"));
        assert!(output.files.contains_key("src/App.tsx"));
        assert!(output.files.contains_key("src/main.tsx"));
        assert!(output.files.contains_key("src/styles.css"));
        assert!(
            output
                .files
                .get("src/App.tsx")
                .unwrap()
                .contains("Todo App")
        );
    }

    #[test]
    fn sanitizes_package_name() {
        assert_eq!(sanitize_package_name("Todo App"), "todo-app");
        assert_eq!(sanitize_package_name("  My_App  "), "my-app");
        assert_eq!(sanitize_package_name("!!!"), "rust-agent-app");
    }

    #[test]
    fn escapes_jsx_text() {
        assert_eq!(
            escape_jsx_text(r#"<script>"x" & 'y'</script>"#),
            "&lt;script&gt;&quot;x&quot; &amp; &#39;y&#39;&lt;/script&gt;"
        );
    }
}
