use crate::agent::flows::traditional::files::sanitize::{escape_jsx_text, sanitize_package_name};

pub fn package_json(project_name: &str) -> String {
    let package = serde_json::json!({
        "scripts": {
            "dev": "vite",
            "build": "vite build",
            "preview": "vite preview"
        },
        "dependencies": {
            "@vitejs/plugin-react": "latest",
            "vite": "latest",
            "react": "latest",
            "react-dom": "latest",
            "typescript": "latest"
        },
        "devDependencies": {},
        "name": sanitize_package_name(project_name),
        "version": "1.0.0"
    });

    serde_json::to_string_pretty(&package).expect("package.json should serialize")
}

pub fn app_tsx(project_name: &str, description: &str) -> String {
    format!(
        r#"import React from "react";
import "./styles.css";

export default function App() {{
  return (
    <main className="app">
      <section className="hero">
        <p className="eyebrow">Generated by rust_agent</p>
        <h1>{}</h1>
        <p>{}</p>
      </section>
    </main>
  );
}}
"#,
        escape_jsx_text(project_name),
        escape_jsx_text(description)
    )
}

pub fn main_tsx() -> String {
    r#"import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
"#
    .to_string()
}

pub fn styles_css() -> String {
    r#"* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: #0f172a;
  color: #f8fafc;
}

.app {
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 48px;
}

.hero {
  width: min(720px, 100%);
  padding: 40px;
  border-radius: 28px;
  background: linear-gradient(135deg, rgba(59, 130, 246, 0.24), rgba(168, 85, 247, 0.24));
  border: 1px solid rgba(255, 255, 255, 0.16);
  box-shadow: 0 24px 80px rgba(15, 23, 42, 0.45);
}

.eyebrow {
  margin: 0 0 12px;
  color: #93c5fd;
  font-size: 14px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}

h1 {
  margin: 0 0 16px;
  font-size: clamp(40px, 8vw, 72px);
  line-height: 1;
}

p {
  margin: 0;
  color: #cbd5e1;
  font-size: 18px;
  line-height: 1.7;
}
"#
    .to_string()
}
